### ISSUE TITLE
Storing words DB

### ISSUE THREAD

**Issue by hyperlapse122** [Team-StarGarden/darakbang-engine#5]
단어 DB를 저장할 곳이 필요합니다.
처음 실행했을 때 시행되었으면 좋겠네요

**Comment by Alex4386** [comment]
처음 실행시 DB 쿼리로 테스트 하고 테스트 fail 시 initialization script 실행을 유도하는 것이 좋을 것 같습니다.

추후 DevOps 를 고려해서도 그게 나을 것 같고요.

**Comment by hyperlapse122** [comment]
@Alex4386 근데 저장 할 곳이 마땅치 않네요
SQL 파일을 분리하고 할까봐요

**Comment by Alex4386** [comment]
cdn.star.garden을 활용하죠.

**Comment by Alex4386** [comment]
wget 같은걸 쓸 방법이 없을까요

**Comment by hyperlapse122** [comment]
Rust로 어느 정도 가능하지 않을까요?
NPM의 script같은 것도 가능한 걸로 아는데

**Comment by hyperlapse122** [comment]
Merge가 완료되어 Close합니다
